### ISSUE TITLE
message serverのレスポンスがnilの時の扱い

### ISSUE THREAD

**Issue by gosyujin** [gosyujin/nicony#13]
see #12

レスポンスがnilだったら次へ？リトライしてみる？

**Comment by gosyujin** [comment]
```
[nicony] 2016-01-11T01:15:09+09:00 [comment.go:getComment:44] [DEBUG] comment server URL: http://msg.nicovideo.jp/43/api/
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2b47]

goroutine 1 [running]:
main.getComment(0xc8202ec38a, 0xa, 0xc8202ec397, 0x3, 0xc8202ec39f, 0x42, 0xc8202ec3e5, 0x2b, 0xc8202ec418, 0x2f, ...)
    /Users/kk_Ataka/Dropbox/_Mac/github/nicony/comment.go:51 +0xb07
main.download(0xc82029521e, 0xa, 0xc8200de380, 0xc8200de410, 0xc8200de440, 0xc8200de3c0, 0xc8200de3f0)
    /Users/kk_Ataka/Dropbox/_Mac/github/nicony/nicony.go:159 +0xb7e
main.main()
    /Users/kk_Ataka/Dropbox/_Mac/github/nicony/nicony.go:65 +0x41b
```

**Comment by gosyujin** [comment]
https://golang.org/pkg/net/http/#Client.Post

**Comment by gosyujin** [comment]
エラーメッセージ拾った

```
Post http://msg.nicovideo.jp/17/api/: read tcp 202.248.110.173:80: connection reset by peer
```

**Comment by gosyujin** [comment]
http://www.drk7.jp/MT/archives/001593.html

> Connection reset by peer エラーの原因はブラウザとサーバ間の通信が切れた事（多くの場合はブラウザが閉じられたもしくはコンテンツを返す前に他のページに遷移済み）によるエラー。

前後にスリープ入れてみる？

**Comment by gosyujin** [comment]
http://builder.japan.zdnet.com/os-admin/20365610/5/

> 6：「connection reset by peer」エラーについてはあまり心配しない
> 
> 　ユーザーが（停止ボタンやエスケープキーを押して）サイトへの要求をキャンセルすると、サーバのログには「connection reset by peer」と記録される。このメッセージが時々しか現れないようなら、おそらく誰かが間違ってアドレスを入力したか、サイトが読み込まれるのを待てなかったとということを意味している。もしこのメッセージを頻繁に見るようなら、サイトが遅くなって混雑問題が起きており、一部の人の忍耐を超えるところまで来ている可能性がある。この問題を生じる別のネットワークの問題を抱えている場合もある。

こういう話もある
